<script type="text/javascript" src="https://d3f5pyioow99x0.cloudfront.net/<?php echo $this->getHullVersion() ?>/hull.js"></script>
<script type="text/javascript">
(function() {
  var HullConfig = <?php echo json_encode($this->getInitConfig())?>;
  Hull.on("hull.auth.logout", function() {
    document.location = "/customer/account/logout";
  });
  Hull.on("hull.auth.login", function() {
    document.location.reload();
  });
  Hull.init(HullConfig);
})();
</script>
